In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.cross_validation import train_test_split
from skimage import img_as_float, img_as_ubyte

/Users/prinklek/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
import skimage

In [3]:
image_path = '/Users/prinklek/Downloads/Capstone_project/fashion-mnist_train.csv'

In [4]:
raw_img_data = pd.read_csv(image_path)

In [5]:
raw_img_data.shape

(59999, 785)

In [6]:
raw_img_data = raw_img_data.drop(raw_img_data.index[-1], axis=0 )

In [7]:
raw_img_data.columns

Index(['2', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.296', '0.297', '0.298', '0.299', '0.300', '0.301', '0.302', '0.303',
       '0.304', '0.305'],
      dtype='object', length=785)

In [8]:
raw_img_data['2'].value_counts()

9    6000
8    6000
6    6000
5    6000
4    6000
3    6000
1    6000
0    6000
7    5999
2    5999
Name: 2, dtype: int64

In [9]:
X = raw_img_data[raw_img_data.columns[1:]].iloc[:].values

In [10]:
X.shape

(59998, 784)

In [11]:
y = raw_img_data['2'].values

In [12]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [13]:
X_train[:5]

array([[  0,   0,   0, ..., 122,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]])

In [228]:
y_train[:5]

array([7, 3, 3, 5, 4])

In [229]:
from skimage import feature
feat_df = pd.DataFrame(np.empty((X_train.shape[0],81)))
for idx, row in enumerate(X_train):
    a = row.reshape(28, 28)
    X_feat = skimage.feature.hog(a)
    feat_df.iloc[idx,:] = X_feat

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [230]:
feat_df.tail(5)

0         1         2         3         4         5         6   \
29994  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29995  0.021508  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29996  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29997  0.018765  0.029351  0.025375  0.021690  0.011951  0.005002  0.003011   
29998  0.017362  0.018328  0.017931  0.007995  0.003836  0.000000  0.004008   

             7         8         9     ...           71        72        73  \
29994  0.000000  0.000000  0.063793    ...     0.125186  0.075065  0.000000   
29995  0.000000  0.000000  0.043610    ...     0.018637  0.034561  0.004703   
29996  0.000000  0.000000  0.000000    ...     0.000000  0.000000  0.000000   
29997  0.005439  0.009554  0.008590    ...     0.002500  0.011987  0.010270   
29998  0.000000  0.000000  0.011001    ...     0.018061  0.035749  0.012488   

             74        75        76        77        78        79        80  
29994  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.027624  
29995  0.006490  0.012318  0.001021  0.000475  0.006026  0.007297  0.027485  
29996  0.000000  0.001804  0.129281  0.001370  0.000000  0.000000  0.000000  
29997  0.008172  0.007001  0.008270  0.006070  0.003961  0.009933  0.015332  
29998  0.011841  0.003793  0.007273  0.011166  0.001919  0.016361  0.020382  

[5 rows x 81 columns]

In [231]:
feat_df.shape

(29999, 81)

In [232]:
X_feat[:5]

array([ 0.0173622 ,  0.01832837,  0.01793085,  0.00799543,  0.00383612])

In [233]:
X_feat.shape

(81,)

In [234]:
y_train.shape

(29999,)

In [235]:
X_train.shape

(29999, 784)

In [236]:
y_test.shape

(29999,)

In [237]:
y_train.shape

(29999,)

In [238]:
from sklearn import linear_model
logr = linear_model.LogisticRegression()

In [239]:
logr.fit(feat_df, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [240]:
logr.score(feat_df, y_train)

0.7678922630754359

In [241]:
from skimage import feature
feat_df_T = pd.DataFrame(np.empty((X_test.shape[0],81)))
for idx, row in enumerate(X_test):
    b = row.reshape(28, 28)
    T_X_feat = skimage.feature.hog(b)
    feat_df_T.iloc[idx,:] = T_X_feat

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [242]:
logr_yhat = logr.predict(feat_df_T)

In [243]:
logr_yhat

array([9, 7, 7, ..., 4, 3, 8])

In [244]:
logr.score(feat_df_T, y_test)

0.76695889862995437

In [245]:
yhat = logr.predict(feat_df) # this is for training set

In [29]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [247]:
print(classification_report(y_train, yhat))

             precision    recall  f1-score   support

          0       0.69      0.82      0.75      2997
          1       0.94      0.94      0.94      3035
          2       0.62      0.64      0.63      3060
          3       0.75      0.80      0.78      2939
          4       0.61      0.70      0.65      3047
          5       0.87      0.83      0.85      2950
          6       0.51      0.28      0.36      3030
          7       0.81      0.88      0.84      2993
          8       0.89      0.90      0.90      2995
          9       0.92      0.91      0.92      2953

avg / total       0.76      0.77      0.76     29999



In [248]:
print(classification_report(y_test,logr_yhat))

             precision    recall  f1-score   support

          0       0.69      0.83      0.75      3003
          1       0.92      0.93      0.93      2965
          2       0.61      0.65      0.63      2939
          3       0.75      0.79      0.77      3061
          4       0.60      0.68      0.64      2953
          5       0.87      0.83      0.85      3050
          6       0.49      0.27      0.35      2970
          7       0.81      0.88      0.84      3006
          8       0.91      0.90      0.90      3005
          9       0.93      0.91      0.92      3047

avg / total       0.76      0.77      0.76     29999



In [249]:
print(confusion_matrix(y_train,yhat))

[[2444   19  122  169   41   16  126    0   60    0]
 [   8 2838   44  101   10    1   28    0    5    0]
 [ 148    3 1972   58  482    2  306    0   89    0]
 [ 146  125   61 2344  156    3   89    0   15    0]
 [  40   17  377  178 2122    3  263    0   47    0]
 [   7    0    0    4    0 2445    0  401   25   68]
 [ 707    9  576  158  641    2  862    0   75    0]
 [   0    0    0    0    0  225    0 2622    3  143]
 [  33    9   37   74   53   44   21    9 2708    7]
 [   0    0    0   19    0   62    0  190    3 2679]]


In [250]:
print(confusion_matrix(y_test,logr_yhat))

[[2478   22  110  170   37    8  132    0   46    0]
 [  14 2772   43  109    6    1   15    0    5    0]
 [ 156    4 1907   62  475    5  262    0   68    0]
 [ 122  164   75 2431  150    7   94    1   17    0]
 [  44   15  368  196 1998    3  294    0   35    0]
 [   4    0    0    5    0 2528    0  418   17   78]
 [ 759   18  571  162  586    9  795    0   70    0]
 [   0    0    0    1    0  240    0 2640    2  123]
 [  32    4   37   74   70   47   26   11 2697    7]
 [   0    1    0   25    0   72    0  185    2 2762]]


In [14]:
from skimage import feature
XTR_feat_df_1 = pd.DataFrame(np.empty((X_train.shape[0],81)))
for idx, row in enumerate(X_train):
    d = row.reshape(28, 28)
    XT_feat_1 = skimage.feature.hog(d)
    XTR_feat_df_1.iloc[idx,:] = XT_feat_1

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [15]:
XTRfeat_df_2 = pd.DataFrame(np.empty((X_train.shape[0],2)))
for idx, row in enumerate(X_train):
    mean_val = np.mean(row)
    median_val = np.median(row)
    XTRfeat_df_2.iloc[idx,0] = mean_val
    XTRfeat_df_2.iloc[idx,1] = median_val

In [16]:
from skimage import feature
XTfeat_df = pd.DataFrame(np.empty((X_test.shape[0],81)))
for idx, row in enumerate(X_test):
    b = row.reshape(28, 28)
    XT_feat = skimage.feature.hog(b)
    XTfeat_df.iloc[idx,:] = XT_feat

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [17]:
XTfeat_df2 = pd.DataFrame(np.empty((X_test.shape[0],2)))
for idx, row in enumerate(X_test):
    mean_val = np.mean(row)
    median_val = np.median(row)
    XTfeat_df2.iloc[idx,0] = mean_val
    XTfeat_df2.iloc[idx,1] = median_val

In [18]:
XTfeat_df.head(5)

0         1         2         3         4         5         6    7   \
0  0.014139  0.000561  0.013153  0.012262  0.010298  0.000155  0.000000  0.0   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.0   
2  0.012478  0.006603  0.009530  0.000000  0.000000  0.005207  0.005747  0.0   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.0   
4  0.001118  0.012639  0.009889  0.026707  0.013652  0.005593  0.000056  0.0   

         8         9     ...           71        72        73        74  \
0  0.000000  0.005833    ...     0.002283  0.006274  0.005015  0.002866   
1  0.000000  0.000000    ...     0.002080  0.007353  0.007349  0.000000   
2  0.000000  0.014228    ...     0.019525  0.027962  0.007241  0.000000   
3  0.000000  0.000000    ...     0.015768  0.002052  0.007835  0.006966   
4  0.003934  0.001326    ...     0.000000  0.009722  0.003515  0.027891   

         75        76        77        78        79        80  
0  0.004427  0.009845  0.003754  0.001468  0.000306  0.000126  
1  0.004413  0.096669  0.035368  0.001416  0.009832  0.000000  
2  0.000000  0.014449  0.013424  0.009044  0.001975  0.013991  
3  0.026054  0.052974  0.019019  0.014149  0.019383  0.006002  
4  0.011905  0.062106  0.032246  0.013399  0.012012  0.001106  

[5 rows x 81 columns]

In [19]:
XTfeat_df2.head(5)

0      1
0  132.776786  198.0
1   41.934949    0.0
2   37.637755    0.0
3   26.880102    0.0
4   41.463010    2.0

In [20]:
import pandas as pd
XTfeat_df3 = pd.concat([XTfeat_df, XTfeat_df2], axis=1) # test

In [21]:
XTRfeat_df_4 = pd.concat([XTR_feat_df_1, XTRfeat_df_2],axis=1) # train 

In [22]:
XTRfeat_df_4.shape

(29999, 83)

In [23]:
XTfeat_df2.shape

(29999, 2)

In [24]:
XTfeat_df.shape

(29999, 81)

In [25]:
from sklearn import linear_model
logr = linear_model.LogisticRegression()
logr.fit(XTRfeat_df_4, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [26]:
logr.score(XTRfeat_df_4, y_train)

0.76469215640521349

In [27]:
lr_yhat_2 = logr.predict(XTRfeat_df_4)

In [30]:
print(confusion_matrix(y_train,lr_yhat_2))

[[2378   18   80  282   31   33  116    1   62    0]
 [   9 2805   34  122    4    5   21    0    4    0]
 [ 103    3 1984   51  439    9  350    0  105    0]
 [  80  178   55 2420  118   38  112    0   17    0]
 [  25   12  351  289 1946    4  320    0   60    0]
 [   7    0    0    6    0 2521    0  337   15   97]
 [ 653   11  614  199  495   28  917    0   94    0]
 [   0    0    0    0    0  273    0 2557    1  128]
 [  24    6   34   89   41   77   24    7 2721    7]
 [   1    0    0   13    0   67    0  168    2 2691]]


In [31]:
logr.score(XTfeat_df3, y_test)

0.76462548751625059

In [32]:
yhat_4 = logr.predict(XTfeat_df3)

In [33]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [34]:
print(classification_report(y_test,yhat_4))

             precision    recall  f1-score   support

          0       0.72      0.79      0.76      2999
          1       0.93      0.93      0.93      2996
          2       0.62      0.65      0.63      2955
          3       0.71      0.82      0.76      2982
          4       0.63      0.66      0.65      2993
          5       0.84      0.84      0.84      3017
          6       0.49      0.29      0.36      2989
          7       0.83      0.86      0.84      3040
          8       0.88      0.89      0.88      2970
          9       0.91      0.91      0.91      3058

avg / total       0.76      0.76      0.76     29999



In [35]:
print(confusion_matrix(y_test,yhat_4))

[[2381   17   96  261   40   26  111    0   67    0]
 [  12 2795   35  113    5    3   26    0    7    0]
 [ 109    5 1906   50  458    7  307    0  113    0]
 [  76  157   46 2442  111   33  101    1   15    0]
 [  28   12  345  245 1966   12  336    0   49    0]
 [   5    0    0    6    0 2538    3  350   12  103]
 [ 661   14  631  207  490   18  859    0  108    1]
 [   0    0    0    0    0  268    0 2609    1  162]
 [  31   13   36  105   32   69   22   10 2648    4]
 [   1    1    0   15    0   61    1  183    2 2794]]


In [36]:
from skimage import feature
XTRfeat_df = pd.DataFrame(np.empty((X_train.shape[0],81)))
for idx, row in enumerate(X_train):
    c = row.reshape(28, 28)
    XTR_feat = skimage.feature.hog(c)
    XTfeat_df.iloc[idx,:] = XT_feat

/Users/prinklek/anaconda3/lib/python3.6/site-packages/skimage/feature/_hog.py:119: skimage_deprecation: Default value of `block_norm`==`L1` is deprecated and will be changed to `L2-Hys` in v0.15
  'be changed to `L2-Hys` in v0.15', skimage_deprecation)


In [37]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [38]:
rf = RandomForestClassifier(n_estimators=500, 
                  max_depth=None, 
                  max_features='auto')
dtc = DecisionTreeClassifier(max_depth=None, 
                             max_features='auto')

dtc.fit(X_train, y_train)
print('dtc acc:', dtc.score(X_test, y_test))

rf.fit(X_train, y_train)
print('rf acc:', rf.score(X_test, y_test))

dtc acc: 0.761958731958
rf acc: 0.876529217641


In [39]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(500)

rfc.fit(X_train, y_train)
print('rfc acc:', rfc.score(X_test, y_test))

rfc acc: 0.876795893196


In [40]:
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(y_test, rfc.predict(X_test)))

[[2549    2   46  104   15    3  258    0   22    0]
 [   8 2899   11   62    4    0   10    0    2    0]
 [  18    0 2377   31  366    2  141    0   20    0]
 [  50   12   17 2722  107    0   66    0    8    0]
 [   2    8  229   83 2514    1  142    0   14    0]
 [   0    0    0    2    0 2897    0   82    9   27]
 [ 501    5  348   73  265    1 1733    0   63    0]
 [   0    0    0    0    0   58    0 2831    1  150]
 [   2    4   14   12   12    4   32    8 2880    2]
 [   0    0    0    0    0   35    0  118    4 2901]]


In [41]:
print(classification_report(y_test, rfc.predict(X_test)))

             precision    recall  f1-score   support

          0       0.81      0.85      0.83      2999
          1       0.99      0.97      0.98      2996
          2       0.78      0.80      0.79      2955
          3       0.88      0.91      0.90      2982
          4       0.77      0.84      0.80      2993
          5       0.97      0.96      0.96      3017
          6       0.73      0.58      0.65      2989
          7       0.93      0.93      0.93      3040
          8       0.95      0.97      0.96      2970
          9       0.94      0.95      0.95      3058

avg / total       0.88      0.88      0.88     29999



In [42]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

std = StandardScaler()
std.fit(X_train)
X_train_std = std.transform(X_train)
X_test_std = std.transform(X_test)

knn = KNeighborsClassifier(2)

knn.fit(X_train_std, y_train)
print(knn.score(X_test_std, y_test))

/Users/prinklek/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


0.834527817594
